// Auto-generated by AFM VFCC CMS — do not edit manually
window.churchData = {
  "events": [],
  "blogs": [
    {
      "title": "Always be prayerful",
      "author": "Ralidzhivha RR",
      "date": "19 Mar 2026",
      "content": "It is important that we always equip ourselves with prayer."
    }
  ],
  "leadersPhoto": "https://ramudzuli1702.github.io/afm_vfcc_web/posters/leaders.jpg",
  "leaders": [
    {
      "name": "Bishop Ramatshimbila",
      "role": "Senior Bishop"
    },
    {
      "name": "Mom Bishop Ramatshimbila",
      "role": "Mom Bishop"
    }
  ],
  "boardPhoto": "https://ramudzuli1702.github.io/afm_vfcc_web/posters/board-photo.jpg",
  "boardMembers": [
    "Abraham Ratshibvumo — Chairperson",
    "Andrew Mavhungu — Deputy Treasurer",
    "Hannah Zulu — Treasurer",
    "Matodzi Ramabulana — Deputy Chairperson",
    "Muofhe Masondo — Additional Board Member",
    "Muvhango Nemavhola — Secretary",
    "Nokuthula Ledwaba — Additional Board Member",
    "Nomvula Mulaudzi — Additional Board Member",
    "Pfunzo Nematandani — Deputy Secretary"
  ],
  "contact": {
    "address": "Kutama Tshikwarani\nKutama\n0940",
    "phone": "+27636202691",
    "phoneHref": "tel:+27636202691",
    "facebookUrl": "",
    "facebookLabel": "",
    "youtubeUrl": "",
    "youtubeLabel": "",
    "email": ""
  }
};
