// Auto-generated by AFM VFCC CMS — do not edit manually
window.churchData = {
  "events": [],
  "blogs": [
    {
      "title": "Always be prayerful",
      "author": "Ralidzhivha RR",
      "date": "19 Mar 2026",
      "content": "It is important that we always equip ourselves with prayer."
    }
  ],
  "leadersPhoto": "",
  "leaders": [],
  "boardPhoto": "",
  "boardMembers": [
    "Abraham Ratshibvumo — Chairperson",
    "Andrew Mavhungu — Deputy Treasurer",
    "Hannah Zulu — Treasurer",
    "Matodzi Ramabulana — Deputy Chairperson",
    "Muofhe Masondo — Additional Board Member",
    "Muvhango Nemavhola — Secretary",
    "Nokuthula Ledwaba — Additional Board Member",
    "Nomvula Mulaudzi — Additional Board Member",
    "Pfunzo Nematandani — Deputy Secretary"
  ]
};
